spring:
  application:
    name: tests_meet_up
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.db_structure_naming_strategy: legacy
  datasource:
    url: jdbc:postgresql://localhost:5432/bbank
    username: postgres
    password: 2029
    driver-class-name: org.postgresql.Driver
